name: Code styles
on:
  push:
  schedule:
    - cron: '0 0 * * THU'

jobs:
  php-cs-fixer:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: php-cs-fixer, cs2pr
      - uses: actions/checkout@v2
      - run: composer install --prefer-dist
      - run: ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --dry-run --using-cache=no --format=checkstyle | cs2pr

  phpmd:
    name: phpmd
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
      - uses: actions/checkout@v2
      - run: composer install --prefer-dist
      - run: ./vendor/bin/phpmd ./ text ./phpmd.xml --suffixes php,inc,test --exclude vendor,bin,tests,examples

#  phpstan:
#    name: phpstan
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '7.4'
#          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
#          tools: phpstan, cs2pr
#      - uses: actions/checkout@v2
#      - run: composer install --prefer-dist
#      - run: ./vendor/bin/phpstan analyse ./src ./tests --error-format=checkstyle | cs2pr

#  psalm:
#    name: psalm
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '7.4'
#          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
#      - uses: actions/checkout@v2
#      - run: composer install --prefer-dist
#      - run: ./vendor/bin/psalm --output-format=github

#  security-checker:
#    name: security-checker
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '7.4'
#          tools: composer:v2
#      - uses: actions/checkout@v2
#      - run: composer install --prefer-dist
#      - uses: symfonycorp/security-checker-action@v3
