name: Tests
on:
  push:
  schedule:
    - cron: '0 0 * * THU'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TRUSTEDSHOPS_LOGIN: ${{ secrets.TRUSTEDSHOPS_LOGIN }}
      TRUSTEDSHOPS_PASS: ${{ secrets.TRUSTEDSHOPS_PASS }}
      TRUSTEDSHOPS_TSID: ${{ secrets.TRUSTEDSHOPS_TSID }}
    strategy:
      matrix:
        php-versions: ['7.4']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          version: 2
      - run: XDEBUG_MODE=coverage ./vendor/bin/phpunit
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
